"""Constants for the SmartNext integration."""

from __future__ import annotations

from typing import Final

DOMAIN: Final = "smartnext"

CONF_UNIT_ID: Final = "unit_id"
CONF_RECONNECT_DELAY: Final = "reconnect_delay"
CONF_SCAN_INTERVAL: Final = "scan_interval"

DEFAULT_PORT: Final = 502
DEFAULT_TIMEOUT: Final = 5.0
DEFAULT_RECONNECT_DELAY: Final = 10.0
DEFAULT_UNIT_ID: Final = 2
DEFAULT_SCAN_INTERVAL: Final = 5

MIN_SCAN_INTERVAL: Final = 2
MAX_SCAN_INTERVAL: Final = 300

PLATFORMS: Final = [
    "sensor",
    "binary_sensor",
    "number",
    "select",
    "switch",
    "button",
]

MANUFACTURER: Final = "AstralPool"
MODEL: Final = "Smart Next"

# Input registers (FC04) - protocol v1.70
IR_ELECTROLYSIS_FUNCTIONAL_TARGET: Final = 0x41
IR_ELECTROLYSIS_PRODUCTION: Final = 0x42
IR_ELECTROLYSIS_CURRENT: Final = 0x43
IR_ELECTROLYSIS_VOLTAGE: Final = 0x44
IR_ELECTROLYSIS_CHLORINE_PRODUCTION: Final = 0x45
IR_ELECTROLYSIS_TOTAL_HOURS_LSB: Final = 0x48
IR_ELECTROLYSIS_TOTAL_HOURS_MSB: Final = 0x49
IR_ELECTROLYSIS_PARTIAL_HOURS_LSB: Final = 0x4A
IR_ELECTROLYSIS_PARTIAL_HOURS_MSB: Final = 0x4B
IR_PH: Final = 0x51
IR_PH_DOSAGE_ELAPSED: Final = 0x57
IR_PH_PUMP_OUTPUT: Final = 0x58
IR_PH_TOTAL_HOURS: Final = 0x5A
IR_PH_PARTIAL_HOURS: Final = 0x5B
IR_ORP: Final = 0x81
IR_TEMPERATURE: Final = 0xB1
IR_SALT: Final = 0xC1

# Holding registers (FC03 / FC06) - protocol v1.70
HR_PRODUCT_CODE_HIGH: Final = 0x04
HR_PRODUCT_CAPACITY: Final = 0x05
HR_TECHNOLOGIES_IMPLEMENTED: Final = 0x06
HR_HARDWARE_VERSION: Final = 0x07
HR_FIRMWARE_VERSION: Final = 0x08
HR_SERIAL_HIGH: Final = 0x09
HR_SERIAL_MIDDLE: Final = 0x0A
HR_SERIAL_LOW: Final = 0x0B
HR_TECHNOLOGIES_ENABLED: Final = 0x0D
HR_FLOW_CONTROL_WORD: Final = 0x30
HR_ELECTROLYSIS_CONTROL_WORD: Final = 0x40
HR_ELECTROLYSIS_NORMAL_SETPOINT: Final = 0x41
HR_ELECTROLYSIS_COVER_SETPOINT: Final = 0x42
HR_ELECTROLYSIS_BOOST_REMAINING: Final = 0x44
HR_PH_INIT_TIME: Final = 0x55
HR_PH_OUTPUT_CONTROL_WORD: Final = 0x56
HR_PH_SETPOINT: Final = 0x57
HR_PH_DOSAGE_LIMIT: Final = 0x58
HR_ORP_SETPOINT: Final = 0x87
HR_TEMPERATURE_CONTROL_WORD: Final = 0xB0
HR_TEMPERATURE_MIN: Final = 0xB2
HR_TEMPERATURE_MAX: Final = 0xB3
HR_SALT_CONTROL_WORD: Final = 0xC0
HR_SALT_MIN: Final = 0xC2
HR_SALT_MAX: Final = 0xC3

# Discrete inputs (FC02) - protocol v1.70
DI_GENERAL_ALARM: Final = 0x200
DI_TREATMENT_HALTED: Final = 0x202

DI_FLOW_GENERAL: Final = 0x240
DI_FLOW_INTERNAL: Final = 0x241
DI_FLOW_EXTERNAL_SWITCH: Final = 0x242

DI_ELECTROLYSIS_CHECK_CELL: Final = 0x250
DI_ELECTROLYSIS_LOW_CONDUCTIVITY: Final = 0x251
DI_ELECTROLYSIS_HIGH_CONDUCTIVITY: Final = 0x252

DI_PH_LOW_ALARM: Final = 0x260
DI_PH_HIGH_ALARM: Final = 0x261
DI_PH_PUMP_STOP_ALARM: Final = 0x266
DI_PH_FUSE_ALARM: Final = 0x267

DI_ORP_LOW_ALARM: Final = 0x270
DI_ORP_HIGH_ALARM: Final = 0x271

DI_TEMPERATURE_LOW_ALARM: Final = 0x280
DI_TEMPERATURE_HIGH_ALARM: Final = 0x281

DI_SALT_LOW_ALARM: Final = 0x290
DI_SALT_HIGH_ALARM: Final = 0x291

DI_ELECTROLYSIS_RUNNING: Final = 0x400
DI_ELECTROLYSIS_POLARITY: Final = 0x401
DI_COVER_INPUT: Final = 0x402
DI_COVER_ACTIVE: Final = 0x403
DI_ELECTROLYSIS_EXTERNAL_CONTROL_INPUT: Final = 0x404
DI_ELECTROLYSIS_INTERNAL_ORP_STOP: Final = 0x405
DI_ELECTROLYSIS_EXTERNAL_CONTROL_STOP: Final = 0x406

DI_FLOW_INTERNAL_STATUS: Final = 0x300
DI_FLOW_EXTERNAL_STATUS: Final = 0x302

DI_PH_INITIALIZING: Final = 0x500
DI_PH_MEASURE_UNRELIABLE: Final = 0x501
DI_PH_DOSING: Final = 0x560

DI_ORP_MEASURE_UNRELIABLE: Final = 0x802
DI_TEMPERATURE_MEASURE_UNRELIABLE: Final = 0xB01
DI_SALT_CURRENT_INSUFFICIENT: Final = 0xC00
DI_SALT_MEASURE_UNRELIABLE: Final = 0xC01
DI_SALT_VOLTAGE_INSUFFICIENT: Final = 0xC02

# Coils (FC05)
# Flow configuration.
COIL_FLOW_INTERNAL_SENSOR_ENABLE: Final = 0x300
COIL_FLOW_EXTERNAL_SENSOR_ENABLE: Final = 0x301

# Electrolysis configuration.
COIL_ELECTROLYSIS_BOOST: Final = 0x401
COIL_ELECTROLYSIS_COVER_CONTROL_ENABLE: Final = 0x402
COIL_ELECTROLYSIS_EXTERNAL_CONTROL_ENABLE: Final = 0x404
COIL_ELECTROLYSIS_INTERNAL_ORP_CONTROL_ENABLE: Final = 0x405
COIL_ELECTROLYSIS_POLARITY_PERIOD_LOW: Final = 0x409
COIL_ELECTROLYSIS_POLARITY_PERIOD_HIGH: Final = 0x40A

# pH output configuration.
COIL_PH_INTELLIGENT_DOSING_ENABLE: Final = 0x566
COIL_PH_PUMP_STOP_ENABLE: Final = 0x56C
# 0x56D is specifically the pH pump-stop rearm, not a global alarm reset.
COIL_PH_PUMP_STOP_RESET: Final = 0x56D

# Temperature and salt alarm configuration.
COIL_TEMPERATURE_LOW_ALARM_ENABLE: Final = 0xB0B
COIL_TEMPERATURE_HIGH_ALARM_ENABLE: Final = 0xB0C
COIL_SALT_LOW_ALARM_ENABLE: Final = 0xC0B
COIL_SALT_HIGH_ALARM_ENABLE: Final = 0xC0C

PH_INIT_ALLOWED_SECONDS: Final = (0, 60, 120, 240)
POLARITY_REVERSAL_ALLOWED_HOURS: Final = (2, 3, 4, 7)
